In [69]:
import numpy as np
from math import exp, pi
data = np.array([[0.6585,0.2444,0],[2.2460,0.5281,0],[-2.7665,-3.8303,0],[-1.2565,3.4912,1],[-0.7973,1.2288,1],[1.1170,2.2637,1]])
class0_data = data[0:3,0:2]
print(class0_data)
class1_data = data[3:6,0:2]
print(class1_data)

[[ 0.6585  0.2444]
 [ 2.246   0.5281]
 [-2.7665 -3.8303]]
[[-1.2565  3.4912]
 [-0.7973  1.2288]
 [ 1.117   2.2637]]


In [70]:
from scipy.stats import norm
class0_feature1_mu, class0_feature1_std = norm.fit(class0_data[:,0].T)
#class0_feature1_mu = np.sum(class0_data[:,0])
class0_feature1_var = norm.var(class0_feature1_mu, class0_feature1_std)
print(class0_feature1_mu)
print(class0_feature1_std)
print(class0_feature1_var)

0.046
2.09167496678
4.37510416667


In [71]:
class0_feature2_mu, class0_feature2_std = norm.fit(class0_data[:,1].T)
#class0_feature2_mu = np.sum(class0_data[:,1])
class0_feature2_var = norm.var(class0_feature2_mu, class0_feature2_std)
print(class0_feature2_mu)
print(class0_feature2_std)
print(class0_feature2_var)

-1.01926666667
1.99107219413
3.96436848222


In [72]:
class1_feature1_mu, class1_feature1_std = norm.fit(class1_data[:,0].T)
#class1_feature1_mu = np.sum(class1_data[:,0])
class1_feature1_var = norm.var(class1_feature1_mu, class1_feature1_std)
print(class1_feature1_mu)
print(class1_feature1_std)
print(class1_feature1_var)

-0.312266666667
1.02788409312
1.05654570889


In [73]:
class1_feature2_mu, class1_feature2_std = norm.fit(class1_data[:,1].T)
#class1_feature2_mu = np.sum(class1_data[:,1])
class1_feature2_var = norm.var(class1_feature2_mu, class1_feature2_std)
print(class1_feature2_mu)
print(class1_feature2_std)
print(class1_feature2_var)

2.3279
0.924735879409
0.855136446667


In [74]:
class0_feature1_pdf = norm.pdf(0, loc=class0_feature1_mu, scale=class0_feature1_std)
print(class0_feature1_pdf)
class0_feature2_pdf = norm.pdf(1, loc=class0_feature2_mu, scale=class0_feature2_std)
print(class0_feature2_pdf)
class1_feature1_pdf = norm.pdf(0, loc=class1_feature1_mu, scale=class1_feature1_std)
print(class1_feature1_pdf)
class1_feature2_pdf = norm.pdf(1, loc=class1_feature2_mu, scale=class1_feature2_std)
print(class1_feature2_pdf)

0.190682503283
0.119807076696
0.370616728258
0.153860760916


In [75]:
prob_y0 = (0.5*class0_feature1_pdf*class0_feature2_pdf)/((0.5*class0_feature1_pdf*class0_feature2_pdf)+ \
                                                         (0.5*class1_feature1_pdf*class1_feature2_pdf))
print(prob_y0)

0.286034138033


In [76]:
prob_y1 = (0.5*class1_feature1_pdf*class1_feature2_pdf)/((0.5*class0_feature1_pdf*class0_feature2_pdf)+ \
                                                         (0.5*class1_feature1_pdf*class1_feature2_pdf))
print(prob_y1)

0.713965861967


In [77]:
import pandas as pd
from sklearn.preprocessing import label_binarize
from sklearn.cross_validation import train_test_split
from sklearn import cross_validation
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [78]:
col_names = ['X0','X1', 'label']
data = pd.DataFrame(data, columns = col_names)
data.head()

X0      X1  label
0  0.6585  0.2444    0.0
1  2.2460  0.5281    0.0
2 -2.7665 -3.8303    0.0
3 -1.2565  3.4912    1.0
4 -0.7973  1.2288    1.0

In [79]:
feature_cols = ['X0', 'X1']
x = data[feature_cols]
y = data.label

In [83]:
# use Gaussian NB to validate results
model_gaussianNB = GaussianNB()
model_gaussianNB.fit(x,y)
predict = np.array([0,1])
predict = predict.reshape(1,-1)
print(model_gaussianNB.predict_proba(predict))

[[ 0.28603414  0.71396586]]
